"""trial reminder flag

Revision ID: 353c56b7c747
Revises: 68112381bacf
Create Date: 2026-06-25 23:11:48.106081
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '353c56b7c747'
down_revision: Union[str, None] = '68112381bacf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_reminder_sent', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('trial_reminder_sent')

    # ### end Alembic commands ###
