"""initial schema

Revision ID: 68112381bacf
Revises: 
Create Date: 2026-06-25 22:49:51.233273
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68112381bacf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('provider', 'admin', name='userrole'), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('nextdoor_handle', sa.String(length=255), nullable=True),
    sa.Column('onboarding_source', sa.String(length=40), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('automation_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('broadcast_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('facebook', 'nextdoor', name='accountprovider'), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'posted', 'failed', name='broadcaststatus'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_broadcast_posts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcast_posts'))
    )
    with op.batch_alter_table('broadcast_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broadcast_posts_user_id'), ['user_id'], unique=False)

    op.create_table('client_pricing_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade', sa.String(length=120), nullable=True),
    sa.Column('service_categories', sa.Text(), nullable=False),
    sa.Column('price_list', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('target_neighborhoods', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_client_pricing_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_pricing_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_client_pricing_profiles_user_id'))
    )
    op.create_table('connected_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('facebook', 'nextdoor', name='accountprovider'), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('auth_method', sa.Enum('oauth', 'managed_business_page', 'session', name='accountauthmethod'), nullable=False),
    sa.Column('encrypted_session', sa.Text(), nullable=True),
    sa.Column('health', sa.Enum('healthy', 'needs_reauth', 'disconnected', 'provisioning', name='connectionhealth'), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_connected_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connected_accounts'))
    )
    op.create_table('lead_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('facebook', 'nextdoor', name='accountprovider'), nullable=False),
    sa.Column('post_url', sa.String(length=512), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('new', 'matched', 'irrelevant', 'drafted', 'engaged', 'dismissed', name='leadstatus'), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lead_matches_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_matches'))
    )
    with op.batch_alter_table('lead_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_matches_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_matches_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('outreach_recruits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('facebook', 'nextdoor', name='accountprovider'), nullable=False),
    sa.Column('profile_url', sa.String(length=512), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('nextdoor_handle', sa.String(length=255), nullable=True),
    sa.Column('converted_user_id', sa.Integer(), nullable=True),
    sa.Column('message_sent', sa.Boolean(), nullable=False),
    sa.Column('trial_signup_at', sa.DateTime(), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['converted_user_id'], ['users.id'], name=op.f('fk_outreach_recruits_converted_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outreach_recruits'))
    )
    with op.batch_alter_table('outreach_recruits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_recruits_dedup_key'), ['dedup_key'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'canceled', name='subscriptionstatus'), nullable=False),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('user_id', name=op.f('uq_subscriptions_user_id'))
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='ticketstatus'), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_tickets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_tickets'))
    )
    op.create_table('agent_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'posted', 'rejected', name='responsestatus'), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead_matches.id'], name=op.f('fk_agent_responses_lead_id_lead_matches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_responses')),
    sa.UniqueConstraint('lead_id', name=op.f('uq_agent_responses_lead_id'))
    )
    op.create_table('support_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], name=op.f('fk_support_messages_ticket_id_support_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_messages'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_messages')
    op.drop_table('agent_responses')
    op.drop_table('support_tickets')
    op.drop_table('subscriptions')
    with op.batch_alter_table('outreach_recruits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_recruits_dedup_key'))

    op.drop_table('outreach_recruits')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('lead_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_matches_user_id'))
        batch_op.drop_index(batch_op.f('ix_lead_matches_dedup_key'))

    op.drop_table('lead_matches')
    op.drop_table('connected_accounts')
    op.drop_table('client_pricing_profiles')
    with op.batch_alter_table('broadcast_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broadcast_posts_user_id'))

    op.drop_table('broadcast_posts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
