"""sms_enabled flag

Revision ID: fd85df171ad4
Revises: 353c56b7c747
Create Date: 2026-06-26 01:27:24.694877
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd85df171ad4'
down_revision: Union[str, None] = '353c56b7c747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sms_enabled')

    # ### end Alembic commands ###
